description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  - "job_content.*"
  - "job.*"
  - 'build'
  - 'serve'
markdown: kramdown
sass:
  sass_dir: assets

assets:
  autowrite: true
  prefix: "/assets"
  assets:
    - "*.ttf"
    - "*.eot"
    - "*.otf"
    - "*.woff"
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/vendor

  features:
    automatic_img_size: false
    liquid: true

data_show:
  - resource_collection: jobs
    path: portfolio